name: azbox
description: Easy and fast internationalization for your Flutter Apps. Translate your apps using AZBox.
homepage: https://github.com/azbox-io/azbox-localization
issue_tracker: https://github.com/azbox-io/azbox-localization/issues

version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  http: ^0.13.0
  shared_preferences: '>=2.0.0 <3.0.0'
  intl: '>=0.17.0-0 <=0.18.1'
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0